name: Release

on:
  push:
    tags:
      - "*"

env:
  WEBSITE_URL: https://meeper.ai/

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Check TypeScript
        run: npm run ts

      - name: Create app build
        run: npm run build

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            dist/ext.zip
